version: "3.9"
services:
  zk1:
    container_name: zk1
    hostname: zk1
    restart: always
    image: zookeeper:3.9.4
    ports:
      - 21811:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk2:
    container_name: zk2
    hostname: zk2
    restart: always
    image: zookeeper:3.9.4
    ports:
      - 21812:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk3:
    container_name: zk3
    hostname: zk3
    restart: always
    image: zookeeper:3.9.4
    ports:
      - 21813:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181; server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
  zoonavigator:
    container_name: zoonavigator
    image: elkozmon/zoonavigator
    ports:
      - 9000:9000
