[workspace]
resolver = "3"
members = [
    "01-intro/anysystem-intro/ping-pong/tests",
    "04-group-comm/seminar/gossip/simulator",
    "homework/01-guarantees/tests",
    "homework/04-broadcast/tests",
    "homework/06-membership/tests",
    "08-scaling/seminar/load-balancing-lab",
    "homework/07-kv-sharding/tests",
    "homework/08-kv-replication/tests",
    "homework/09-kv-replication-2/tests",
]
